[[pages]]
path = "intro.py"
name = "Introduction"
icon = "ğŸ "

[[pages]]
path = "pages/0_tools.py"
name = "Must-know"
icon = "ğŸ› "

[[pages]]
path = "pages/1_cake_eating.py"
name = "Cake Eating"
icon = "ğŸ°"