[[pages]]
path = "intro.py"
name = "Introduction"
icon = "ğŸ "


[[pages]]
path = "pages/1_glossary.py"
name = "Glossary"
icon = "ğŸ”®"

# [[pages]]
# path = "pages/2_tools.py"
# name = "Must-know"
# icon = "ğŸ› "

[[pages]]
path = "pages/3_cake_eating_finite.py"
name = "Cake Eating - Finite"
icon = "ğŸ‚"

[[pages]]
path = "pages/4_cake_eating_infinite.py"
name = "Cake Eating - Infinite"
icon = "ğŸ°"